### ISSUE TITLE
Wrong link to npm packages

### ISSUE THREAD

**Issue by ajwillshire** [CompositionalIT/feliz-ag-grid#1]
On the bindings section here: https://compositionalit.github.io/feliz-ag-grid/
the links take you to the wrong packages.
Also, it would be good to have a reminder that you need to install a bunch of npm packages before the wrapper works. It probably seems obvious, but if someone hasn't done much web development before then it would be useful.

**Comment by teknikal-wizard** [comment]
Hi Andrew :)

Which link is incorrect? I tried the npm link and it takes me to ag-grid-react.

Regarding the dependent packages - you shouldn't need to hunt them down youself.

```
cd ./project
femto install Feliz.AgGrid
```

This should gather and install all the things you need.

If you can confirm that this resolves your issue, i'll close this ticket down (or try to help further otherwise!)
