### ISSUE TITLE
Missing method `cellEditor` in ColumnDef

### ISSUE THREAD

**Issue by TerenceHinrichsen** [CompositionalIT/feliz-ag-grid#4]
Just want to check whether this awesome library is being maintained?
I want to add a "select" component to my grid, and according to [these docs](https://www.ag-grid.com/react-data-grid/cell-editors/) I need to pass a custom component to the `cellEditor`. 

Am I missing it somewhere? Sorry if it is a stupid question.

**Comment by theprash** [comment]
FYI you might want to consider using `cellRendererFramework`, which is already implemented. It's a different approach where you completely take over the rendering of the cell, even if it isn't being edited, rather than allowing ag-grid to render the cell until you double click to edit. This way, all rows would show a select in the column when the grid loads.

Adding `cellEditor` would be good too because it has different advantages.

**Comment by zwpdbh** [comment]
Found how to use the cellRendererFramework:


```
 ColumnDef.create<string> [
            ColumnDef.cellRendererFramework (fun _v row ->
                Html.a [
                    prop.text row.Id
                    prop.onClick (fun _ ->
                        printfn $"{row.Id}"
                    )
                ]
            )
            ColumnDef.filter RowFilter.Text
            ColumnDef.headerName "ID"
        ]
```

**Comment by theprash** [comment]
Thanks for that @zwpdbh. I'm going to add an example column to the demo code in the repo as well

**Comment by theprash** [comment]
@zwpdbh The [demo](https://compositionalit.github.io/feliz-ag-grid/) now uses more functionality including `cellRendererFramework`.
